version: '3'

services:
  pool:
    image: funkypenguin/turtle-pool
    volumes:
      - ./config:/config

  redis:
    container_name: redis
    volumes:
      - ./config:/config
    image: redis
    entrypoint: |
      redis-server /config/redis.conf

